%chapter = (
     'chapnum' => 8,
     'title'  =>"Chapter 8 -- Statement Logic: Proofs",
     'sections' => "1 2 3 4 5 6 999 ",
     'sec1' => {
          'title'  => "Implicational Rules of Inference",
          'labels' => {
                "8.1A" => "A. Annotating Proofs",
                "8.1B" => "B. Correct or Incorrect?",
                "8.1C" => "C. Proofs",
                "8.1D" => "D. More Proofs",
		"8.1E" => "E. Still More Proofs",
                "8.1F" => "F. English Arguments  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.1F: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.1F).')\">[why?]</span>",
                "8.1G" => "G. More English Arguments  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.1G: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.1G).')\">[why?]</span>",
          },
          'counts' => {
                "8.1A" => "10",
                "8.1B" => "20",
                "8.1C" => "20",
                "8.1D" => "25",
                "8.1E" => "30",
		"8.1F" => "0",
		"8.1G" => "0",
          },
     },
     'sec2' => {
          'title'  => "Five Equivalence Rules",
          'labels' => {
                "8.2A" => "A. Annotating Proofs",
                "8.2B" => "B. Correct or Incorrect?",
                "8.2C" => "C. Proofs",
                "8.2D" => "D. Longer Proofs",
		"8.2E" => "E. More Proofs",
                "8.2F" => "F. English Arguments  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.2F: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.2F).')\">[why?]</span>",
          },
          'counts' => {
                "8.2A" => "15",
                "8.2B" => "20",
                "8.2C" => "25",
                "8.2D" => "25",
                "8.2E" => "25",
                "8.2F" => "0",
          },
     },
     'sec3' => {
          'title'  => "Five More Equivalence Rules",
          'labels' => {
                "8.3A" => "A. Annotating proofs",
                "8.3B" => "B. Correct or Incorrect?",
                "8.3C" => "C. Short Proofs",
                "8.3D" => "D. Longer Proofs",
		"8.3E" => "E. More Proofs",
                "8.3F" => "F. English Arguments - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.3F: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.3F).')\">[why?]</span>",
          },
          'counts' => {
                "8.3A" => "10",
                "8.3B" => "20",
                "8.3C" => "25",
                "8.3D" => "25",
                "8.3E" => "25",
                "8.3F" => "0",
          },
     },
     'sec4' => {
          'title'  => "Conditional proof",
          'labels' => {
                "8.4A" => "A. Conditional Proof",
                "8.4B" => "B. More Conditional Proofs",
                "8.4C" => "C. English Arguments  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.4C: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.4C).')\">[why?]</span>",
                "8.4D" => "D. More English Arguments  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.4D: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.4D).')\">[why?]</span>",
                "8.4E" => "E. Valid or Invalid?  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.4E: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.4E).')\">[why?]</span>",
          },
          'counts' => {
                "8.4A" => "25",
                "8.4B" => "25",
                "8.4C" => "0",
                "8.4D" => "0",
                "8.4E" => "0",
          },
     },
     'sec5' => {
          'title'  => "Reductio ad Absurdum",
          'labels' => {
                "8.5A" => "A. Proofs",
                "8.5B" => "B. Valid or Invalid?",
		"8.5C" => "C. More Proofs",
                "8.5D" => "D. English Arguments - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.5D: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.5D).')\">[why?]</span>",
                "8.5E" => "E. More English Arguments - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.5E: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.5E).')\">[why?]</span>",
                "8.5F" => "F. Valid or Invalid?  - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.5F: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.5F).')\">[why?]</span>",
          },
          'counts' => {
                "8.5A" => "20",
                "8.5B" => "5",
                "8.5C" => "30",
                "8.5D" => "0",
                "8.5E" => "0",
                "8.5F" => "0",
          },
     },
     'sec6' => {
          'title'  => "Proving Theorems",
          'labels' => {
                "8.6A" => "A. Theorems",
                "8.6B" => "B. Challenging Theorems",
                "8.6C" => "C. Corresponding Conditionals - not available online  <span style=\"color:#666666; font-size:9px\" onMouseOver=\"this.style.cursor=\'pointer\'\" onClick=\"alert('EXERCISE 8.6C: There are two possible reasons why this exercise is unavailable: either it is too open ended to be checked by software or it combines elements of other exercises for which there is already ample opportunity to practice.  If you believe this exercise could and should be online, please send your request by email to webmaster\@poweroflogic.com. Be sure to identify the exercise number (8.6C).')\">[why?]</span>",
          },
          'counts' => {
                "8.6A" => "20",
                "8.6B" => "10",
                "8.6C" => "10",
          },
     },
     'sec999' => {
          'title'  => "Additional Practice",
          'labels' => {
                "RYO_XP" => "Create Your own Proof",
          },
          'counts' => {
                "RYO_XP" => "1000",
          },
     },
);
